# Generated by Django 5.2.7 on 2025-11-01 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_commentproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='cover',
            field=models.ImageField(blank=True, upload_to='product/product_cover', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='comment author'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime created'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime modified'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='stars',
            field=models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'normal'), ('4', 'good'), ('5', 'perfect')], max_length=10, verbose_name='comment stars'),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='text',
            field=models.TextField(verbose_name='comment text'),
        ),
    ]
