# Generated by Django 5.2.7 on 2025-11-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_commentproduct_cover_alter_commentproduct_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentproduct',
            name='cover',
        ),
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='product/product_cover', verbose_name='image'),
        ),
    ]
